/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void takeSample(GButton source, GEvent event) { //_CODE_:sampleButton:691472:
  //if (placedCat != null) {    
  //  String[] dnaData = placedCat.loadDnaProfile();

  //  for (int i = 0; i < samples.size() ; i ++) {
  //    Sample s = samples.get(i);    
  //    if (s.filled == false) {
        
  //      s.dnaSequence = dnaData;
  //      s.cat = placedCat;
  //      s.filled = true;
        
  //      break;
  //    }
  //  }
      
  //  placedCat = null;
  //}
  
  loadTestSamples();
  
} //_CODE_:sampleButton:691472:

public void caseSelected(GDropList source, GEvent event) { //_CODE_:caseDropdown:955074:
  println("caseDropdown - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:caseDropdown:955074:

public void showCaseInfo(GButton source, GEvent event) { //_CODE_:caseButton:275004:
  int selectedIndex = caseDropdown.getSelectedIndex();
 
  caseKitten = kittens.get(selectedIndex);
  updateInformationBox();
} //_CODE_:caseButton:275004:

public void enzymeSelected(GDropList source, GEvent event) { //_CODE_:enzymeDropdown:210050:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:enzymeDropdown:210050:

public void removeSample(GButton source, GEvent event) { //_CODE_:retakeButton:320982:
  placedCat = null;
} //_CODE_:retakeButton:320982:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:528241:
  appc.background(230);
} //_CODE_:window1:528241:

public void infoChanged(GTextArea source, GEvent event) { //_CODE_:infoBox:755543:
  println("infoBox - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:infoBox:755543:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  sampleButton = new GButton(this, 374, 485, 80, 30);
  sampleButton.setText("SCAN");
  sampleButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  sampleButton.addEventHandler(this, "takeSample");
  label1 = new GLabel(this, 610, 80, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Select Case");
  label1.setOpaque(false);
  caseDropdown = new GDropList(this, 610, 110, 340, 100, 4, 10);
  caseDropdown.setItems(loadStrings("list_955074"), 0);
  caseDropdown.addEventHandler(this, "caseSelected");
  caseButton = new GButton(this, 610, 140, 100, 30);
  caseButton.setText("See Case Info");
  caseButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  caseButton.addEventHandler(this, "showCaseInfo");
  label2 = new GLabel(this, 610, 190, 150, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Select Restriction Enzyme");
  label2.setOpaque(false);
  enzymeDropdown = new GDropList(this, 610, 220, 340, 80, 3, 10);
  enzymeDropdown.setItems(loadStrings("list_210050"), 0);
  enzymeDropdown.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  enzymeDropdown.addEventHandler(this, "enzymeSelected");
  retakeButton = new GButton(this, 343, 550, 112, 39);
  retakeButton.setText("Retake Sample");
  retakeButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  retakeButton.addEventHandler(this, "removeSample");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 350, 800, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  infoBox = new GTextArea(window1, 20, 60, 300, 300, G4P.SCROLLBARS_NONE);
  infoBox.setOpaque(true);
  infoBox.addEventHandler(this, "infoChanged");
  label3 = new GLabel(window1, 20, 30, 120, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Information Box");
  label3.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton sampleButton; 
GLabel label1; 
GDropList caseDropdown; 
GButton caseButton; 
GLabel label2; 
GDropList enzymeDropdown; 
GButton retakeButton; 
GWindow window1;
GTextArea infoBox; 
GLabel label3; 
